
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author laurence
 */
public class main_welcome extends javax.swing.JFrame {
    
product_class prodc = new product_class();
int Prid=0;
    /**
     * Creates new form main_welcome
     */
    public main_welcome() {
        initComponents();jLabel1.setText("WELCOME!");
        showRefresh();
    }
    public void searchProd(){
        String prodname = srchprd.getText();
        try{
           String sql = "select * from products where PRODUCT_NAME like ?;";
           Class.forName("com.mysql.jdbc.Driver");
           Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost/formreg?", "root", "");
           PreparedStatement pstmt = conn.prepareStatement(sql);
           pstmt.setString(1, "%"+prodname+"%");
           ResultSet rs = pstmt.executeQuery();
           DefaultTableModel tbl = (DefaultTableModel)labtab.getModel();
           tbl.setRowCount(0);
           if(!rs.isBeforeFirst()){
               tbl.addRow(new Object[]{"NO DATA", "NO DATA", "NO DATA", "NO DATA"});
           }else{
                while(rs.next()){
                    tbl.addRow(new Object[]{rs.getString("ID"),rs.getString("PRODUCT_NAME"),rs.getString("QUANTITY"),rs.getString("PRICE")});
                }
           }
        } catch (ClassNotFoundException ex) {
        Logger.getLogger(main_welcome.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(main_welcome.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    public void showRefresh(){
        String sql = "select * from products;";
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost/formreg?", "root", "");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            DefaultTableModel l = (DefaultTableModel)labtab.getModel();
            l.setRowCount(0);
            while(rs.next()){
                l.addRow(new Object[]{rs.getInt("ID"),rs.getString("PRODUCT_NAME"),rs.getInt("QUANTITY"),rs.getString("PRICE")});
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(main_welcome.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(main_welcome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addProd = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pdlab = new javax.swing.JTextField();
        qtlab = new javax.swing.JSpinner();
        prilab = new javax.swing.JFormattedTextField();
        abt = new javax.swing.JButton();
        aqtbt = new javax.swing.JButton();
        PrId = new javax.swing.JLabel();
        ebt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        labtab = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        srchprd = new javax.swing.JTextField();

        addProd.setMinimumSize(new java.awt.Dimension(460, 340));

        jLabel2.setText("PRODUCT NAME:");

        jLabel3.setText("QUANTITY:");

        jLabel4.setText("PRICE:");

        qtlab.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        prilab.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        abt.setText("ADD");
        abt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abtActionPerformed(evt);
            }
        });

        aqtbt.setText("ADD QTY");

        PrId.setText("jLabel5");

        ebt.setText("EDIT");
        ebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ebtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addProdLayout = new javax.swing.GroupLayout(addProd.getContentPane());
        addProd.getContentPane().setLayout(addProdLayout);
        addProdLayout.setHorizontalGroup(
            addProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addProdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(addProdLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(qtlab))
                    .addGroup(addProdLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pdlab, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addProdLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(prilab)))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(addProdLayout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addGroup(addProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ebt, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addGroup(addProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(abt, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addComponent(aqtbt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PrId, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        addProdLayout.setVerticalGroup(
            addProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addProdLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(addProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pdlab, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(addProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(qtlab)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(addProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(prilab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(abt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrId, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ebt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aqtbt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("WELCOME!");

        labtab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "PRODUCT NAME", "QUANTITY", "PRICE"
            }
        ));
        jScrollPane1.setViewportView(labtab);

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("EDIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("SEARCH:");

        srchprd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                srchprdKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(srchprd))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(10, 10, 10))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(srchprd, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

addProd.setVisible(true);
addProd.setLocationRelativeTo(this);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void abtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abtActionPerformed
String pdname = pdlab.getText();
int qty = (int)qtlab.getValue();
String pri = prilab.getText();

product_class pdcl = new product_class();
int tati = pdcl.Add(pdname, qty, pri);
showRefresh();
if(tati==1){
    JOptionPane.showMessageDialog(rootPane, "SUCCESSFULLY ADDED");
}else{
    
}
pdlab.setText("");

prilab.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_abtActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
int selRow = labtab.getSelectedRow();
if (selRow== -1){
    JOptionPane.showMessageDialog(labtab, "Please Select Name From Table To Remove." , "Message",JOptionPane.WARNING_MESSAGE);
}
 else{
    String name = labtab.getValueAt(selRow,1).toString();
    int opt = JOptionPane.showConfirmDialog(labtab, "ARE YOU SURE YOU WANT TO DELETE\n"+name,"WARNING", JOptionPane.YES_OPTION);
    if( opt== JOptionPane.YES_OPTION){
        int a = JOptionPane.showConfirmDialog(labtab," THIS WILL DELETE\n"+name,"Confirmation",JOptionPane.ERROR_MESSAGE, JOptionPane.OK_CANCEL_OPTION );
        if (a== JOptionPane.OK_OPTION){
            int ii = Integer.parseInt(labtab.getValueAt(selRow, 0).toString());
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/formreg?", "root", "");
                String sql = "Delete from products where ID = ?; ";
                PreparedStatement pstmt = con.prepareStatement(sql);
                pstmt.setInt(1, ii);
                pstmt.executeUpdate();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(main_welcome.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(main_welcome.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(labtab, "Product_name" +name+ "DELETED");
        }else{
            
        }
    }else{
        
    }
}
showRefresh();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
int row = labtab.getSelectedRow();
if(row==-1){
    JOptionPane.showMessageDialog(labtab, "PLEASE SELECT DATA ON THE TABLE","ERROR",JOptionPane.ERROR_MESSAGE);
}else{
    int opti = JOptionPane.showConfirmDialog(labtab, "ARE YOU SURE YOU WANT TO EDIT THIS DATA?","CONFIRMATION",JOptionPane.YES_NO_OPTION);
    if(opti==JOptionPane.YES_OPTION){
    String id = labtab.getValueAt(row, 0).toString();
    String prodname = labtab.getValueAt(row, 1).toString();
    String qu = labtab.getValueAt(row, 2).toString();
    String popri = labtab.getValueAt(row, 3).toString();
    PrId.setText(id);
    pdlab.setText(prodname);
    qtlab.setToolTipText(qu);
    prilab.setText(popri);
}
    this.setVisible(false);
    addProd.setVisible(true);
}
addProd.setVisible(true);this.setVisible(false);addProd.setLocationRelativeTo(null);abt.setVisible(false);ebt.setVisible(true);qtlab.setEnabled(false);aqtbt.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ebtActionPerformed
int id = Integer.parseInt(PrId.getText());
String prdname = pdlab.getText();
String prqu = qtlab.getToolTipText();
String prci = prilab.getText();

try{
    String sql = "update products set PRODUCT_NAME=?, PRICE=? where ID=?;";
    Class.forName("com.mysql.jdbc.Driver");
    Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost/formreg?", "root", "");
    PreparedStatement pstmt = conn.prepareStatement(sql);
   
    pstmt.setString(1, prdname);
    pstmt.setString(2, prci);
    pstmt.setInt(3, id);
    if(pdlab.getText().equals("") || prilab.getText().equals("")){
       JOptionPane.showMessageDialog(addProd, "PLEASE FILL UP ALL FIELDS","WARNING",JOptionPane.WARNING_MESSAGE);  
     }else{
        pstmt.executeUpdate();
        pdlab.setText("");
        prilab.setText("");
        addProd.setVisible(false);
        main_welcome mnp = new main_welcome();
        mnp.setVisible(true); 
    }
}   catch (ClassNotFoundException ex) {
        Logger.getLogger(main_welcome.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(main_welcome.class.getName()).log(Level.SEVERE, null, ex);
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_ebtActionPerformed

    private void srchprdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_srchprdKeyReleased
searchProd();        // TODO add your handling code here:
    }//GEN-LAST:event_srchprdKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PrId;
    private javax.swing.JButton abt;
    private javax.swing.JFrame addProd;
    private javax.swing.JButton aqtbt;
    private javax.swing.JButton ebt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable labtab;
    private javax.swing.JTextField pdlab;
    private javax.swing.JFormattedTextField prilab;
    private javax.swing.JSpinner qtlab;
    private javax.swing.JTextField srchprd;
    // End of variables declaration//GEN-END:variables
}
